apiVersion: v1
kind: Pod 
metadata: 
 name: blue-pod 
 labels: 
  app: blue
spec: 
 containers: 
  - name: blue-cont
    image: abhipraydh96/blue:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata: 
  name: blue-service
spec: 
 selector:
  app: blue
 ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
 type: ClusterIP
