apiVersion: v1
kind: Pod 
metadata: 
 name: green-pod 
 labels: 
  app: green
spec: 
 containers: 
  - name: green-cont
    image: abhipraydh96/green:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata: 
  name: green-service
spec: 
 selector:
  app: green
 ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
 type: ClusterIP
